import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { project } from '../src/project'
import type { ContributionSource, Scenario } from '../src/types'
import { TEST_RULES } from './helpers'

/**
 * Cross-language fuzz (§11): 300 randomized scenarios generated by the
 * Python reference (reproducible seed) spanning the full input space.
 * The TS engine must match every case TO THE CENT. A single mismatch is
 * a bug in one of the two implementations — investigate, never widen
 * the tolerance. Regenerate: python3 reference/generate_fuzz.py
 */

interface FuzzCase {
  scenario: {
    asOf: string
    birthDate: string
    includeSeed: boolean
    annualReturn: number
    returnIsReal: boolean
    annualInflation: number
    annualFee: number
    annualVolatility: number
    targetAgeMonths: number
    sources: {
      id: string
      kind: ContributionSource['kind']
      stepUpRate: number
      schedule: {
        type: 'monthly' | 'annual' | 'once'
        amountCents: string
        startAgeMonths: number
        endAgeMonths: number
        monthOfYear: number
        atAgeMonths: number
      }
    }[]
  }
  months: number
  finalNominalCents: string
  finalRealCents: string
  contributedCents: string
  seedCents: string
  growthCents: string
  warningCount: number
  excessTotalCents: string
  midpointNominalCents: string
}

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../../reference/fixtures/fuzz.json',
)
const corpus = JSON.parse(readFileSync(fixturePath, 'utf8')) as { cases: FuzzCase[] }

function toScenario(f: FuzzCase['scenario']): Scenario {
  return {
    schemaVersion: 1,
    asOf: f.asOf,
    child: { birthDate: f.birthDate },
    includeSeed: f.includeSeed,
    targetAgeMonths: f.targetAgeMonths,
    rules: TEST_RULES,
    assumptions: {
      annualReturn: f.annualReturn,
      returnIsReal: f.returnIsReal,
      annualInflation: f.annualInflation,
      annualFee: f.annualFee,
      annualVolatility: f.annualVolatility,
    },
    sources: f.sources.map((s) => {
      const source: ContributionSource = {
        id: s.id,
        kind: s.kind,
        schedule:
          s.schedule.type === 'monthly'
            ? {
                type: 'monthly',
                amountCents: BigInt(s.schedule.amountCents),
                startAgeMonths: s.schedule.startAgeMonths,
                endAgeMonths: s.schedule.endAgeMonths,
              }
            : s.schedule.type === 'annual'
              ? {
                  type: 'annual',
                  amountCents: BigInt(s.schedule.amountCents),
                  monthOfYear: s.schedule.monthOfYear,
                  startAgeMonths: s.schedule.startAgeMonths,
                  endAgeMonths: s.schedule.endAgeMonths,
                }
              : {
                  type: 'once',
                  amountCents: BigInt(s.schedule.amountCents),
                  atAgeMonths: s.schedule.atAgeMonths,
                },
      }
      if (s.stepUpRate > 0) source.stepUpRate = s.stepUpRate
      return source
    }),
  }
}

describe('fuzz corpus — 300 random scenarios match Python to the cent', () => {
  it('all cases match exactly', () => {
    const failures: string[] = []
    corpus.cases.forEach((c, i) => {
      const p = project(toScenario(c.scenario))
      const checks: [string, string, string][] = [
        ['months', String(p.months), String(c.months)],
        ['finalNominal', String(p.nominalCents[p.months]), c.finalNominalCents],
        ['finalReal', String(p.realCents[p.months]), c.finalRealCents],
        ['contributed', String(p.breakdown.contributedCents), c.contributedCents],
        ['seed', String(p.breakdown.seedCents), c.seedCents],
        ['growth', String(p.breakdown.growthCents), c.growthCents],
        ['warnings', String(p.warnings.length), String(c.warningCount)],
        ['excess', String(p.warnings.reduce((a, w) => a + w.excessCents, 0n)), c.excessTotalCents],
        ['midpoint', String(p.nominalCents[Math.floor(p.months / 2)]), c.midpointNominalCents],
      ]
      for (const [field, got, want] of checks) {
        if (got !== want) failures.push(`case ${i} ${field}: got ${got}, want ${want}`)
      }
    })
    expect(corpus.cases.length).toBe(300)
    expect(failures, failures.slice(0, 10).join('\n')).toEqual([])
  })
})
