import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { monteCarlo } from '../src/montecarlo'
import { project } from '../src/project'
import { buildContributionStream } from '../src/schedule'
import type { ContributionSource, Scenario } from '../src/types'
import { TEST_RULES } from './helpers'

/**
 * Golden-value tests (§11.2): the TS engine must reproduce the fixtures
 * generated by the independent Python reference implementation EXACTLY,
 * to the cent — including Monte-Carlo percentiles for fixed seeds.
 * Regenerate fixtures with: python3 reference/generate_golden.py
 */

interface FixtureSource {
  id: string
  kind: ContributionSource['kind']
  stepUpRate: number
  schedule: {
    type: 'monthly' | 'annual' | 'once'
    amountCents: string
    startAgeMonths: number
    endAgeMonths: number
    monthOfYear: number
    atAgeMonths: number
  }
}

interface FixtureScenario {
  asOf: string
  birthDate: string
  includeSeed: boolean
  annualReturn: number
  returnIsReal: boolean
  annualInflation: number
  annualFee: number
  annualVolatility: number
  targetAgeMonths: number
  sources: FixtureSource[]
}

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../../reference/fixtures/golden.json',
)
const golden = JSON.parse(readFileSync(fixturePath, 'utf8')) as {
  deterministic: Record<
    string,
    {
      scenario: FixtureScenario
      months: number
      startAgeMonths: number
      nominalCentsByMonth: Record<string, string>
      realCentsByMonth: Record<string, string>
      milestones: { ageMonths: number; nominalCents: string; realCents: string }[]
      breakdown: Record<string, string>
      warningCount: number
      excessTotalCents: string
    }
  >
  monteCarlo: Record<
    string,
    {
      scenario: FixtureScenario
      seed: number
      paths: number
      sampleAgesMonths: number[]
      percentileCents: string[][]
      percentileRealCents: string[][]
    }
  >
}

function toScenario(f: FixtureScenario): Scenario {
  return {
    schemaVersion: 1,
    asOf: f.asOf,
    child: { birthDate: f.birthDate },
    includeSeed: f.includeSeed,
    targetAgeMonths: f.targetAgeMonths,
    rules: TEST_RULES,
    assumptions: {
      annualReturn: f.annualReturn,
      returnIsReal: f.returnIsReal,
      annualInflation: f.annualInflation,
      annualFee: f.annualFee,
      annualVolatility: f.annualVolatility,
    },
    sources: f.sources.map((s) => {
      const source: ContributionSource = {
        id: s.id,
        kind: s.kind,
        schedule:
          s.schedule.type === 'monthly'
            ? {
                type: 'monthly',
                amountCents: BigInt(s.schedule.amountCents),
                startAgeMonths: s.schedule.startAgeMonths,
                endAgeMonths: s.schedule.endAgeMonths,
              }
            : s.schedule.type === 'annual'
              ? {
                  type: 'annual',
                  amountCents: BigInt(s.schedule.amountCents),
                  monthOfYear: s.schedule.monthOfYear,
                  startAgeMonths: s.schedule.startAgeMonths,
                  endAgeMonths: s.schedule.endAgeMonths,
                }
              : {
                  type: 'once',
                  amountCents: BigInt(s.schedule.amountCents),
                  atAgeMonths: s.schedule.atAgeMonths,
                },
      }
      if (s.stepUpRate > 0) source.stepUpRate = s.stepUpRate
      return source
    }),
  }
}

describe('golden vectors — deterministic projection matches Python to the cent', () => {
  for (const [name, fix] of Object.entries(golden.deterministic)) {
    it(name, () => {
      const p = project(toScenario(fix.scenario))
      expect(p.months).toBe(fix.months)
      expect(p.startAgeMonths).toBe(fix.startAgeMonths)
      for (const [t, cents] of Object.entries(fix.nominalCentsByMonth)) {
        expect(p.nominalCents[Number(t)], `nominal month ${t}`).toBe(BigInt(cents))
      }
      for (const [t, cents] of Object.entries(fix.realCentsByMonth)) {
        expect(p.realCents[Number(t)], `real month ${t}`).toBe(BigInt(cents))
      }
      expect(
        p.milestones.map((m) => ({
          ageMonths: m.ageMonths,
          nominalCents: m.nominalCents.toString(),
          realCents: m.realCents.toString(),
        })),
      ).toEqual(fix.milestones)
      expect(p.breakdown.contributedCents.toString()).toBe(fix.breakdown.contributedCents)
      expect(p.breakdown.seedCents.toString()).toBe(fix.breakdown.seedCents)
      expect(p.breakdown.growthCents.toString()).toBe(fix.breakdown.growthCents)
      expect(p.warnings.length).toBe(fix.warningCount)
      const excess = p.warnings.reduce((acc, w) => acc + w.excessCents, 0n)
      expect(excess.toString()).toBe(fix.excessTotalCents)
    })
  }
})

describe('golden vectors — Monte Carlo percentiles match Python exactly', () => {
  for (const [name, fix] of Object.entries(golden.monteCarlo)) {
    it(name, () => {
      const mc = monteCarlo(toScenario(fix.scenario), fix.seed, fix.paths)
      expect(mc.sampleAgesMonths).toEqual(fix.sampleAgesMonths)
      expect(mc.percentileCents.map((row) => row.map((v) => v.toString()))).toEqual(
        fix.percentileCents,
      )
      expect(mc.percentileRealCents.map((row) => row.map((v) => v.toString()))).toEqual(
        fix.percentileRealCents,
      )
    })
  }
})

describe('fixture sanity', () => {
  it('covers the required edge matrix', () => {
    const names = Object.keys(golden.deterministic)
    expect(names).toContain('zero-rates-age18')
    expect(names).toContain('cap-exceeding-two-sources')
    expect(names).toContain('employer-overcap')
    expect(names).toContain('max-age-119')
    expect(names).toContain('no-seed-born-2024')
    expect(names.length).toBeGreaterThanOrEqual(10)
  })

  it('cap-exceeding fixture produces warnings in both implementations', () => {
    const fix = golden.deterministic['cap-exceeding-two-sources']
    expect(fix).toBeDefined()
    expect(fix?.warningCount).toBeGreaterThan(0)
    const stream = buildContributionStream(toScenario((fix as NonNullable<typeof fix>).scenario))
    expect(stream.warnings.length).toBe(fix?.warningCount)
  })
})
